version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago
    open-pull-requests-limit: 0
    groups:
      npm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago
    open-pull-requests-limit: 0
    groups:
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    labels:
      - dependencies
