export type { RunnerType } from "../config/index.js";
export type { TaskLineageInput } from "./tasks/provision.js";
export type { TaskCreationOptions } from "./tasks/create.js";
export type {
  TaskType,
  TaskStatus,
  TaskPRStatus,
  TaskPromptSource,
  TaskCheckResult,
  TaskChecks,
  TaskPullRequestCheck,
  TaskPullRequestComment,
  TaskPullRequestReviewDecision,
  TaskPullRequest,
  TaskPR,
  TaskArtifacts,
  RunnerSessionState,
  TaskPtyTabKind,
  TaskPtyTabRecord,
  RunnerSession,
  TaskLastCommit,
  TaskCleanup,
  ProjectTaskRepoTargetStatus,
  ProjectTaskRepoTarget,
  TaskRecord,
  TaskInspection,
  CommandCreateTaskResult,
  CommandListResult,
  CommandAddTaskLinkResult,
  CommandListTaskLinksResult,
  CommandShowTaskResult,
  TaskContextSource,
  ResolvedTaskContext,
  CommandCurrentTaskResult,
  TaskPrCommandDisposition,
  CommandTaskPrResult,
  CommandLogsResult,
  CommandDiffResult,
  CommandOpenResult,
  CommandChecksResult,
  CommandCommitResult,
} from "./types.js";

// re-export validators for external test use
export { validateTaskRecord, normalizeLegacyTaskRecord } from "./tasks/validate.js";

// re-export for UI layer access through the domain boundary (not the private adapter path)
export { readTask, writeTask, mutateTask } from "./adapters/task-store.js";
export { getTaskPrimaryPr } from "./prs/state.js";
export { GitHubRateLimitError } from "./prs/errors.js";
export { assertTaskWorktreeExists } from "./tasks/inspect.js";

import {
  allocateTaskId,
  allocateTaskIdForRepo,
  allocateProjectTaskId,
  listTasks,
  sortTasksForDisplay,
  resolveSelectedTaskId,
  resolveArtifactPath,
  getTask,
  assertTaskWorktreeExists,
  resolveTaskLogPath,
  buildTaskInspection,
  provisionTask,
  provisionProjectTask,
  createDefaultTaskPtyTabs,
  createTask,
  showTask,
  showTaskDiff,
  prepareTaskLogs,
  streamTaskLogs,
  runChecks,
  commitTask,
  closeTask,
  cleanupTask,
  addTaskLink,
  listTaskLinks,
  openTask,
  markRunnerFailed,
  recordStartupFailure,
  markTaskStarted,
  resolveTaskContext,
} from "./tasks/index.js";

import {
  getTaskPrimaryPr,
  isPrTerminal,
  upsertTaskPr,
  deriveTaskStatusFromPrs,
  isMergeReady,
  summarizeRequiredChecks,
  normalizePr,
  writePrStatusArtifact,
  refreshTrackedPullRequest,
  refreshPullRequestChecks,
  discoverOrRefreshAllProjectPullRequests,
  discoverOrRefreshPullRequests,
  discoverOrRefreshPullRequest,
  showTaskPullRequests,
  discoverTaskPullRequest,
  linkTaskPullRequest,
  refreshTaskPullRequest,
  unlinkTaskPullRequest,
  mergeTask,
} from "./prs/index.js";

export const taskService = {
  // task ops
  listTasks,
  getTask,
  provisionTask,
  provisionProjectTask,
  createTask,
  showTask,
  showTaskDiff,
  prepareTaskLogs,
  streamTaskLogs,
  runChecks,
  commitTask,
  closeTask,
  cleanupTask,
  addTaskLink,
  listTaskLinks,
  sortTasksForDisplay,
  resolveSelectedTaskId,
  allocateTaskId,
  allocateTaskIdForRepo,
  allocateProjectTaskId,
  createDefaultTaskPtyTabs,
  assertTaskWorktreeExists,
  resolveTaskLogPath,
  buildTaskInspection,
  resolveArtifactPath,
  openTask,
  markRunnerFailed,
  recordStartupFailure,
  markTaskStarted,
  resolveContext: resolveTaskContext,
  prs: {
    refresh: refreshTrackedPullRequest,
    refreshChecks: refreshPullRequestChecks,
    discoverOrRefresh: discoverOrRefreshPullRequest,
    discoverOrRefreshAll: discoverOrRefreshAllProjectPullRequests,
    discoverOrRefreshMany: discoverOrRefreshPullRequests,
    show: showTaskPullRequests,
    discover: discoverTaskPullRequest,
    link: linkTaskPullRequest,
    refreshAssociation: refreshTaskPullRequest,
    unlink: unlinkTaskPullRequest,
    merge: mergeTask,
    // pure state helpers
    getPrimaryPr: getTaskPrimaryPr,
    isPrTerminal,
    isMergeReady,
    deriveTaskStatus: deriveTaskStatusFromPrs,
    upsertPr: upsertTaskPr,
    normalizePr,
    summarizeRequiredChecks,
    writePrStatusArtifact,
  },
};
