export type {
  RunnerType,
  TaskType,
  TaskStatus,
  TaskPRStatus,
  TaskPromptSource,
  TaskCheckResult,
  TaskChecks,
  TaskPullRequestCheck,
  TaskPullRequestComment,
  TaskPullRequestReviewDecision,
  TaskPullRequest,
  TaskPR,
  TaskArtifacts,
  RunnerSessionState,
  TaskPtyTabKind,
  TaskPtyTabRecord,
  RunnerSession,
  TaskLastCommit,
  TaskCleanup,
  ProjectTaskRepoTargetStatus,
  ProjectTaskRepoTarget,
  TaskRecord,
} from "./types.js";

// re-export validators for external test use
export { validateTaskRecord, normalizeLegacyTaskRecord } from "./tasks/validate.js";

import {
  allocateTaskId,
  allocateTaskIdForRepo,
  allocateProjectTaskId,
  listTasks,
  sortTasksForDisplay,
  resolveSelectedTaskId,
  resolveArtifactPath,
  getTask,
  assertTaskWorktreeExists,
  resolveTaskLogPath,
  buildTaskInspection,
  provisionTask,
  provisionProjectTask,
  createDefaultTaskPtyTabs,
  createTask,
  showTask,
  showTaskDiff,
  prepareTaskLogs,
  streamTaskLogs,
  runChecks,
  commitTask,
  closeTask,
  cleanupTask,
  addTaskLink,
  listTaskLinks,
  attachTask,
  focusTask,
  openTask,
} from "./tasks/index.js";

import {
  getTaskPrimaryPr,
  isPrTerminal,
  upsertTaskPr,
  deriveTaskStatusFromPrs,
  isMergeReady,
  summarizeRequiredChecks,
  normalizePr,
  writePrStatusArtifact,
  refreshTrackedPullRequest,
  refreshPullRequestChecks,
  discoverOrRefreshAllProjectPullRequests,
  discoverOrRefreshPullRequests,
  discoverOrRefreshPullRequest,
  mergeTask,
} from "./prs/index.js";

export const taskService = {
  // task ops
  listTasks,
  getTask,
  provisionTask,
  provisionProjectTask,
  createTask,
  showTask,
  showTaskDiff,
  prepareTaskLogs,
  streamTaskLogs,
  runChecks,
  commitTask,
  closeTask,
  cleanupTask,
  addTaskLink,
  listTaskLinks,
  sortTasksForDisplay,
  resolveSelectedTaskId,
  allocateTaskId,
  allocateTaskIdForRepo,
  allocateProjectTaskId,
  createDefaultTaskPtyTabs,
  assertTaskWorktreeExists,
  resolveTaskLogPath,
  buildTaskInspection,
  resolveArtifactPath,
  attachTask,
  focusTask,
  openTask,
  prs: {
    refresh: refreshTrackedPullRequest,
    refreshChecks: refreshPullRequestChecks,
    discoverOrRefresh: discoverOrRefreshPullRequest,
    discoverOrRefreshAll: discoverOrRefreshAllProjectPullRequests,
    discoverOrRefreshMany: discoverOrRefreshPullRequests,
    merge: mergeTask,
    // pure state helpers
    getPrimaryPr: getTaskPrimaryPr,
    isPrTerminal,
    isMergeReady,
    deriveTaskStatus: deriveTaskStatusFromPrs,
    upsertPr: upsertTaskPr,
    normalizePr,
    summarizeRequiredChecks,
    writePrStatusArtifact,
  },
};
